### ISSUE TITLE
How to use your code

### ISSUE THREAD

**Issue by user419927** [mikhel1984/ext_observer#1]
Hello, I'm a student. I can't master the process when I use your code. I see your matlab file, c++ file and makefile, but I don't understand the running process. I hope you can give me some explanation. Thank you.

**Comment by mikhel1984** [comment]
Hello! Assume, you are working in C++.
1. Define dynamics of your robot, using inheritance from the class **RobotDynamics** (from _/lib/extrnal_observer.h_). It should provide methods **getM**, **getC** and **getG**. Calculation of these matrices is up to you, it can be done theoretically and translated into C code. Another option is definition of dynamics using NMEA algorithm, in this case the base class is **RobotDynamicsRnea**, and the only mandatory method is **rnea**. 
2. Create torque observer of desired type, list of available observers can be found in the _lib_ directory. Each observer takes dynamics object as a first argument and a set of configuration parameters depending on its algorithm. 
3. You should be able to read position, velocity and torque from each joint of a robot. Pass them into the method **getExternalTroque** to get current estimation of external torques.

For more details look at [UR](https://github.com/mikhel1984/ext_observer/blob/9e0db47c2eda42cb5015cdc4c2d5a70d3c278525/ur/test.cpp#L39) implementation or [rnea](https://github.com/mikhel1984/ext_observer/blob/1cd2457f6811f45a5c82cea5b6ba475f8192e384/tests/test_rnea.cpp#L26) test.

**Comment by user419927** [comment]
Thank you for your reply！I know a little about your code framework, but I still have the following questions. I hope I can get some advice from you.


1 .I can't run your test file. There are some problems with my vscode software or matlab software. I want to get some suggestions from you. Before I run your test&nbsp; normally, which software should I choose or which software environment should I configure, or because I need to supplement some other codes such as the&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dynamic&nbsp; parameters you mentioned, I can run your test file normally.In addition, including when those makefile files need to work, and what roles to play are still&nbsp; &nbsp; somewhat confusing. For example, when I run test.m, I will encounter the problem of not finding observers.so
2.I noticed that you have a matlab file. Is its function to call each of your observer methods in turn to draw a comparison diagram?However, there will be many&nbsp; &nbsp; &nbsp; &nbsp; errors to be solved when my matlab runs your test.m, but I can't tell whether my matlab needs to be configured or the cpp file needs to be modified. I hope you can&nbsp; give me some suggestions.
3.&nbsp;Then I noticed your updated ur folder, and I also used ur5 to identify the dynamic parameters of the manipulator.and I use the iterative least square method. I&nbsp; &nbsp; &nbsp; want to get some suggestions from you on how to correctly bring the identified parameters into your code for use.
Thank you very much for your patient reply. I have read your article carefully and benefited a lot.I feel grateful and admired for your spirit of making code open source.I would appreciate it if you could take time to reply to my trivial questions during your busy schedule.


陈杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikhel1984/ext_observer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月18日(星期三) 下午3:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikhel1984/ext_observer] How to use your code (Issue #1)





 
Hello! Assume, you are working in C++.
  
Define dynamics of your robot, using inheritance from the class RobotDynamics (from /lib/extrnal_observer.h). It should provide methods getM, getC and getG. Calculation of these matrices is up to you, it can be done theoretically and translated into C code. Another option is definition of dynamics using NMEA algorithm, in this case the base class is RobotDynamicsRnea, and the only mandatory method is rnea.
 
Create torque observer of desired type, list of available observers can be found in the lib directory. Each observer takes dynamics object as a first argument and a set of configuration parameters depending on its algorithm.
 
You should be able to read position, velocity and torque from each joint of a robot. Pass them into the method getExternalTroque to get current estimation of external torques.
  
For more details look at UR implementation or rnea test.

**Comment by mikhel1984** [comment]
The library was tested on Linux platform. You should have **Eigen3** c++ library for matrix operations. The test code uses **gnuplot**  for visualization. Everything could be compiled with **make** system.  For example, to run C++ example it is enough to do:
```bash
cd ext_observer/tests
make test
```
In the case of compilation error check correctness of _INCDIR_ variable. In other to work in Matlab you need first to build dynamic library _observers.so_:
```bash 
cd ext_observer/matlab
make
```
The library was tested with Matlab2018, I'm not sure if it works correctly with another versions. 

Numerical parameters for UR robot are defined in the file _ur/ur_robot.cpp_. _fricLst_ defines 3 friction parameters for each joint (3x6), rgdLst contains 10 parameters for each joint (10x6). It allows to change only dynamic parameters, since geometry is embedded into auto-generated code for matrix calculation (like C_mtrx_fcn etc).

If you are working in Matlab, maybe the [repo](https://github.com/shamilmamedov/dynamic_calibration) of my colleague could be more useful for you.

**Comment by mikhel1984** [comment]
I close this issue, feel free to write me in case of questions.
